language: python

os:
- linux

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python -m pytest --cov=./fiesta
  - cd docs
  - sphinx-apidoc -o source/ ../fiesta
  - make html
  - cd -

after_success:
  - codecov

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/build/html
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard